server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.222:8848 #配置Nacos地址
#        server-addr: 192.168.10.222:8060 #配置Nacos地址  //nginx nacos 集群配置地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

