server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:kusebingtang/springcloud-config_2020.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config_2020
      ####读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-center-3344
    prefer-ip-address: true     #访问路径可以显示IP地址



